.section .application,"x",@nobits
.global __application_start
__application_start:

.section .bootloader,"x",@nobits
.global __bootloader_start
__bootloader_start:
	nop
	nop
.global __vector_1
__vector_1:
	nop
	nop
.global __vector_2
__vector_2:
	nop
	nop
.global __vector_3
__vector_3:
	nop
	nop
.global __vector_4
__vector_4:
	nop
	nop
.global __vector_5
__vector_5:
	nop
	nop
.global __vector_6
__vector_6:
	nop
	nop
.global __vector_7
__vector_7:
	nop
	nop
.global __vector_8
__vector_8:
	nop
	nop
.global __vector_9
__vector_9:
	nop
	nop
.global __vector_10
__vector_10:
	nop
	nop
.global __vector_11
__vector_11:
	nop
	nop
.global __vector_12
__vector_12:
	nop
	nop
.global __vector_13
__vector_13:
	nop
	nop
.global __vector_14
__vector_14:
	nop
	nop
.global __vector_15
__vector_15:
	nop
	nop
.global __vector_16
__vector_16:
	nop
	nop
.global __vector_17
__vector_17:
	nop
	nop
.global __vector_18
__vector_18:
	nop
	nop
.global __vector_19
__vector_19:
	nop
	nop
.global __vector_20
__vector_20:
	nop
	nop
.global __vector_21
__vector_21:
	nop
	nop
.global __vector_22
__vector_22:
	nop
	nop
.global __vector_23
__vector_23:
	nop
	nop
.global __vector_24
__vector_24:
	nop
	nop
.global __vector_25
__vector_25:
	nop
	nop

.section .optiboot
.global __optiboot_start
__optiboot_start:
